### ISSUE TITLE
No such file or directory: 'coffeelint'

### ISSUE THREAD

**Issue by Cottin** [alin23/Cup#4]
Just installed using Package Control and if I `Show Console` I see this error every time I save a `.coffee` file.

Everything seems to work though, just a bit annoying to know that these errors keep happening :)

MasOS X Big Sur

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1088, in run_
    return self.run(edit)
  File "/Users/victor/Library/Application Support/Sublime Text 3/Installed Packages/Cup.sublime-package/CoffeeScript.py", line 401, in run
  File "/Users/victor/Library/Application Support/Sublime Text 3/Installed Packages/Cup.sublime-package/CoffeeScript.py", line 53, in run
  File "/Users/victor/Library/Application Support/Sublime Text 3/Installed Packages/Cup.sublime-package/CoffeeScript.py", line 91, in _run
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1448, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'coffeelint'
```

**Comment by alin23** [comment]
Try this: `npm install -g coffeelint`

I think I forgot to write that under dependencies.

**Comment by Cottin** [comment]
Thanks but doesn't seem to work. Still get same errors.
I'm running `nvm` though, could that have anything to do with it?

**Comment by alin23** [comment]
Yes, it's possible that Sublime doesn't have the same PATH variable as your shell so it can't see the binaries installed by npm.

I usually start Sublime using the `subl` binary from the terminal to make sure it inherits the same PATH.

**Comment by Cottin** [comment]
Starting with `subl` didn't seem to resolve it either.

In terminal:

```
> echo $PATH
/Users/victor/.nvm/versions/node/v15.12.0/bin:......`
> subl .
```

In Sublime Console:

```
> import os
> os.environ
environ({..., 'PATH': '/Users/victor/.nvm/versions/node/v15.12.0/bin:...', 'NVM_BIN': '/Users/victor/.nvm/versions/node/v15.12.0/', ...}
```

What's weird is that from Sublime Console I can run `coffeelint`:

```
>>> from subprocess import check_output
>>> check_output(['python', '--version'])
b''
>>> check_output(['node', '--version'])
b'v15.12.0\n'
>>> check_output(['coffeelint', '--version'])
b'2.1.0\n'
```
But still same error when saving .coffee file.

Any more suggestions for troubleshooting? 😊

**Comment by alin23** [comment]
Indeed, there was code that was overriding the PATH var. I fixed that in v1.2.2 here: https://github.com/alin23/Cup/commit/04032e9071cd273d4da7e82e91e5930c69cd5960

Upgrade the package through Package Control to get this fix.
